name: GitHub Stats
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [ "master", "main" ]

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Language Stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          user: oOSatyamOo
          template: classic
          base: ""
          config_timezone: Asia/Kolkata
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          filename: generated/languages.svg

      - name: Generate Overview Stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          user: oOSatyamOo
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata
          filename: generated/overview.svg
# name: GitHub Stats
# on:
#   schedule:
#     - cron: "0 0 * * *" # Runs every day at midnight
#   workflow_dispatch: # Allows you to run it manually

# jobs:
#   update-stats:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Generate Stats
#         uses: jstrieb/github-stats@master
#         env:
#           ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#       - name: Commit and Push
#         run: |
#           git config --global user.name "github-actions[bot]"
#           git config --global user.email "github-actions[bot]@users.noreply.github.com"
#           git add generated/*.svg
#           git commit -m "Update GitHub stats" || exit 0
#           git push
# # This is a basic workflow to help you get started with Actions

# name: CI

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v4

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
